# Generated by Django 3.2.25 on 2024-09-10 10:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='brand_images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور')], max_length=10)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='type_images/%Y/%m/%d')),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_img', models.ImageField(blank=True, upload_to='type_images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.IntegerField(choices=[(0.9, '10%'), (0.8, '20%'), (0.75, '25%'), (0.7, '30%'), (0.65, '35%'), (0.55, '45%'), (0.5, '50%'), (0.4, '60%'), (0.25, '75%')])),
                ('new_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('img', models.ImageField(upload_to='product_images/{ptype}/{brand}/%Y/%m/%d')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='shop.brand')),
                ('ptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='shop.ptype')),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-publish'], name='shop_produc_publish_e85d6e_idx'),
        ),
    ]
