# Generated by Django 3.2.25 on 2024-09-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptype',
            name='sub_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
