# Generated by Django 3.2.25 on 2024-09-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_ptype_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.IntegerField(blank=True, choices=[(0.9, '10%'), (0.8, '20%'), (0.75, '25%'), (0.7, '30%'), (35, '35%'), (0.55, '45%'), (0.5, '50%'), (0.4, '60%'), (0.25, '75%')]),
        ),
    ]
