# Generated by Django 3.2.25 on 2024-09-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.IntegerField(blank=True, choices=[(10, '10%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (45, '45%'), (50, '50%'), (60, '60%'), (75, '75%')]),
        ),
    ]
