# Generated by Django 3.2.25 on 2024-09-10 14:00

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/brand_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to=shop.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='ptype',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/type_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ptype',
            name='sub_img',
            field=models.ImageField(blank=True, upload_to='media/type_images/%Y/%m/%d'),
        ),
    ]
