# Generated by Django 5.1 on 2024-09-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20240910_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptype',
            name='img',
            field=models.ImageField(blank=True, upload_to='E:/django/multishop/media/type_images/%Y/%m/%d'),
        ),
    ]
