# Generated by Django 5.1 on 2024-09-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_ptype_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(blank=True, upload_to='E:/django/multishop/media/brand_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ptype',
            name='sub_img',
            field=models.ImageField(blank=True, upload_to='E:/django/multishop/media/type_images/%Y/%m/%d'),
        ),
    ]
