# Generated by Django 5.1 on 2024-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_brand_img_alter_ptype_sub_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.IntegerField(blank=True, choices=[(0, '0%'), (10, '10%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (45, '45%'), (50, '50%'), (60, '60%'), (75, '75%')], default=0),
        ),
    ]
