# Generated by Django 5.1 on 2024-09-13 11:15

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(max_length=3000, upload_to=shop.models.product_image_path),
        ),
    ]
