# Generated by Django 5.1 on 2024-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
    ]
