# Generated by Django 5.1 on 2024-09-20 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_new_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='categories_images/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='ptype',
            name='sub_img',
        ),
        migrations.RemoveField(
            model_name='ptype',
            name='sub_name',
        ),
        migrations.AddField(
            model_name='ptype',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.categories'),
            preserve_default=False,
        ),
    ]
