# Generated by Django 5.1 on 2024-09-20 10:02

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_categories_remove_ptype_sub_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(upload_to='brand_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ptype',
            name='img',
            field=models.ImageField(upload_to=shop.models.ptype_image_path),
        ),
    ]
