# Generated by Django 5.1 on 2024-09-20 11:59

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_brand_img_alter_ptype_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(upload_to=shop.models.brand_image_path),
        ),
    ]
